name: Lint and style checks

on:
  pull_request:
    branches:
      main

jobs:
  backend:
    name: Backend check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - working-directory: backend
      run: |
        npm ci
        npm run lint-check
  frontend:
    name: Frontend check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - working-directory: frontend
      run: |
        npm ci
        npm run lint-check
